### PR TITLE
Add `displayException` to InterpreterError instance

### PR DESCRIPTION
**Pull request by sid-kap**

### CODE REVIEW

**Comment by mvdan** [comment]
Sorry, what problem is this solving? Could you provide an example?

**Comment by sid-kap** [comment]
Since base 4.8, there is a function called `displayException` where you can specify how to pretty-print your exception, to make it easier to read. The default implementation of `displayException` is `show`. For example, I might use `catch` and then do `putStrLn (displayException err)` instead of `putStrLn (show err)`.

The output of `displayError err` currently, since it is using `show` as the default, would be something like 
```
WontCompile (GhcError "<interactive>:3:40:\n    Ambiguous occurrence ‘QDiagram’\n    It could refer to either ‘Diagrams.Prelude.QDiagram’,\n                             imported from ‘Diagrams.Prelude’\n                             (and originally defined in ‘diagrams-core-1.3.0.4:Diagrams.Core.Types’)\n                          or ‘Diagrams.Core.Types.QDiagram’,\n                             imported from ‘Diagrams.Core.Types’)
```
while, with this change, the output of `displayException err` would be something like
```
<interactive>:3:40:
    Ambiguous occurrence ‘QDiagram’
    It could refer to either ‘Diagrams.Prelude.QDiagram’,
                             imported from ‘Diagrams.Prelude’
                             (and originally defined in ‘diagrams-core-1.3.0.4:Diagrams.Core.Types’)
                          or ‘Diagrams.Core.Types.QDiagram’,
                             imported from ‘Diagrams.Core.Types’
```

In my case, I would like to use this with Shake. If my build process (which uses Hint) fails and throws an exception, I want Shake to pretty-print my error using the `displayException` function.

**Comment by mvdan** [comment]
Sounds good! Thanks for the patch.

Please add yourself to the `AUTHORS` file too.

**Comment by sid-kap** [comment]
Added my name to AUTHORS. Thanks!

**Pull request merged**
