### PR TITLE
Proxy

### PR DESCRIPTION
**Pull request by strake**

### CODE REVIEW

**Comment by gelisam** [comment]
It's the standard way to specify types everywhere else (except with a lowercase `proxy` please), but obviously it's a breaking change, so: is it worth breaking people's code?

**Comment by mvdan** [comment]
We can technically break people's code in `0.8.0` since this is pre-1.0, but I wouldn't do that unless necessary.

What is the purpose of this change? Does it improve hint or your usage of it in any way?

**Comment by strake** [comment]
Specifying a type with bottom seems heinous, which is why Proxy was invented.

We could define these functions taking a proxy in another module (and keep the ones taking a value), but i'm not sure what to call it...

**Comment by mvdan** [comment]
I'm not sure I understand - is this change purely to make the API nicer and simpler? If so, we could apply this change for 1.0 (with @gelisam's suggestions and with the build actually succeeding). But it seems unnecessary to me to break user's programs in 0.8 or 0.9.

**Comment by strake** [comment]
@mvdan 

> I'm not sure I understand - is this change purely to make the API nicer and simpler?

Yes

> If so, we could apply this change for 1.0 (with @gelisam's suggestions and with the build actually succeeding). But it seems unnecessary to me to break user's programs in 0.8 or 0.9.

I was hesitating to invest more effort while you seemed inclined to reject the PR anyhow. If you think you might merge it let me know and i'll do it.

**Comment by mvdan** [comment]
Makes sense - thanks for the reply. I still think it's unnecessary to break user's code continuously, so it would be best to group all of these cleanups and deprecation removals in 1.0. It's likely that a pull request done now would have conflicts by then, and this pull request isn't finished, so I'm going to close it for now.

I've instead opened an issue (see above) to make a number of API breaking changes in 1.0 all at once, including this one.

**Pull request closed without merging**
